# This file was generated by GoReleaser. DO NOT EDIT.
class ComplianceMasonry < Formula
  desc "Compliance Masonry is a command-line interface (CLI) that allows users to construct certification documentation using the OpenControl Schema."
  homepage "https://github.com/opencontrol/compliance-masonry"
  url "https://github.com/opencontrol/compliance-masonry/releases/download/v1.2.0/compliance-masonry_1.2.0_darwin_amd64.tar.gz"
  version "1.2.0"
  sha256 "bf09439cba7d2f14f3a6ca2f1697f6e52d1ab28f274a42000c671a07c78524c8"

  def install
    bin.install "compliance-masonry", "masonry"
  end
end
