# This file was generated by GoReleaser. DO NOT EDIT.
class ComplianceMasonry < Formula
  desc "Compliance Masonry is a command-line interface (CLI) that allows users to construct certification documentation using the OpenControl Schema."
  homepage "https://github.com/opencontrol/compliance-masonry"
  url "https://github.com/opencontrol/compliance-masonry/releases/download/v1.2.0/compliance-masonry_1.2.0_darwin_amd64.tar.gz"
  version "1.2.0"
  sha256 "a4c760bba72ce083e88deb51eae6951d7a436e17ae59f174546e5449d6862a69"

  def install
    bin.install "compliance-masonry", "masonry"
  end
end
